baseurl: ""
url: "/"
markdown: kramdown
source: "src"
destination: "public"

collections:
  portfolio-items:
    output: true
    permalink: /portfolio/:path/

#gems:
#  - octopress-paginate

exclude:
  - node_modules
