baseurl: ""
url: "https://nomadevents.com"
markdown: kramdown
source: "src"
destination: "public"

collections:
  - portfolio_items

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
#  - octopress-paginate

exclude:
  - node_modules
